// Batch -3
// Ram Karnani 2012B3A7750P
// Akath Singh Dua 2012B4A7333P

#include "codegen.c"


int main(int argc, char* argv[])
{

	createParseTable();
	fillRHS();
	if(argc < 3){
		printf("\n");
		printf("INSUFFICIENT ARGUMENTS. TRY AGAIN!\n");
		printf("\n");
		return;
	}

	int userinput;
	printf("\n");
	printf("\n");

	printf("LEVEL 4: Lexer / Parser / AST / Symbol Table / Semantic Rules / Type Checking / Code Generation Modules Work.\n");
	printf("COMPILE, GENERATE ASM CODE AND RUN PROGRAM.\n\n");

	printf("Hello User!\n");

	printf("Please enter the desired options\n");
	printf("1 :  To display the token list generated by the lexer(on Console).\n");
	printf("2 :  For parsing to verify the syntactic correctness of the input source code and to produce the parse tree(on Console).\n");
	printf("3 :  To display the Abstract Syntax Tree in depth first order in appropriate format(on Console).\n");
	printf("4 :  To display the amount of allocated memory and number of nodes in Parse Tree and AST for the test case used.\n");
	printf("5 :  To display the Symbol Table.\n");
	printf("6 :  For compiling (front end only) to verify the syntactic and semantic correctness of the input source code.\n");
	printf("7 :  To produce assembly code.\n");

	printf("\n");
	printf("\n");

	scanf("%d",&userinput);

	switch(userinput){

		case 1: printTokenList(argv[1]);
				break;

		case 2:	parseInputSourceCode(argv[1]);
				printParseTree(rootptr);
				break;

		case 3:
				parseInputSourceCode(argv[1]);
				if(parseError==0 && lexError==0){
					setSentinel(rootptr);
					printAST(astroot,NULL);
				}
				break;
		case 4:
				parseInputSourceCode(argv[1]);			
				if(parseError==0 && lexError==0){
					calculateSizeParseTree(rootptr);
					setSentinel(rootptr);
					printRatios();
				}
				break;

		case 5:
				parseInputSourceCode(argv[1]);	
				if(parseError==0 && lexError==0){
					setSentinel(rootptr);
					fillSymbolTable();
					printSymbolTable();
				}
				break;


		case 6: 
				parseInputSourceCode(argv[1]);
				if(parseError==0 && lexError==0){
					setSentinel(rootptr);
					fillSymbolTable();
					semantics();
					semanticErr();
					funErr();
				}
				break;

		case 7: 
				parseInputSourceCode(argv[1]);
				if(parseError==0 && lexError==0){
					setSentinel(rootptr);
					fillSymbolTable();
					semantics();
					semanticErr();
					funErr();
					if(semanticError==0){
						printf("\n");
						printf("\tTo run the ASM file, enter the following command, say your ASM file is \"code.asm\"\n");
						printf("\tnasm -f elf64 -l code.lst  code.asm && gcc -o code code.o\n");
						printf("\t./code\n");
						printf("\n");
						codegeneration(argv[2]);
					}
				}
				break;
		default:
			break;

	}


}
